[package]
name = "raftpb"
version = "0.1.0"
authors = ["Hung Tran"]
description = "Example project using prost-build"
edition = "2018"

[dependencies]
bytes = "1.6"
prost = "0.14"
protobuf = "3"

[build-dependencies]
prost-build = "0.14"
