name: build
run-name: ${{ github.actor }} building cargo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - run: apt install -y protobuf-compiler && cargo build 
  # TODO: add clippy
